### ISSUE TITLE
Feature Request "change domain type"

### ISSUE THREAD

**Issue by Svenum** [AshleyYakeley/NixVirt#18]
I would define my own "template" and therefor I need the option to change the domain type from:

`<domain type="kvm">` to `<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">` 

And then I need the option to add qemu commands at the bottom:

```xml
...
  <qemu:commandline>
    <qemu:arg value="-cpu"/>
    <qemu:arg value="host,kvm=off,hv_vendor_id=null"/>
    <qemu:arg value="-machine"/>
    <qemu:arg value="q35"/>
  </qemu:commandline>
</domain>
```

**Comment by AshleyYakeley** [comment]
Would it work to do the namespace this way?
```
<qemu:commandline xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0>
  <qemu:arg value="-cpu"/>
  <qemu:arg value="host,kvm=off,hv_vendor_id=null"/>
  <qemu:arg value="-machine"/>
  <qemu:arg value="q35"/>
</qemu:commandline>
```

**Comment by Svenum** [comment]
It seems , that this would work.

**Comment by AshleyYakeley** [comment]
Will add a way to do this.
https://libvirt.org/kbase/qemu-passthrough-security.html

**Comment by AshleyYakeley** [comment]
Done. See [this file](/AshleyYakeley/NixVirt/blob/master/checks/domain/template-windows-2/input.nix) for an example.

Reopen if this doesn't work.

**Comment by Svenum** [comment]
Ok, I will try tomorrow. One Question left. Is there any tool or so to convert an existing XML to Nix? I know I could just use the XML but I think its easyer to debug nix then the xml file. :)

**Comment by Svenum** [comment]
Ok, but thanks

**Comment by Svenum** [comment]
@AshleyYakeley I got the following error:
`NixVirt: libvirt error: internal error: missing domain type attribute`

**Comment by Svenum** [comment]
I'm just incompetent and forgot `type="kvm"` XD
Sorry for the trouble. :joy:
