### ISSUE TITLE
Feature Request: Domain Disk Backing Store support

### ISSUE THREAD

**Issue by diamondburned** [AshleyYakeley/NixVirt#34]
I can file a PR for this, but I have some questions:

- `backingStore`'s `source` block is the same as the upper-level `source` block. Should `source` be moved into `let..in`?
- `backingStore` is recursive (it can be nested infinitely). What's the preferred way of doing this?
- The `subelem` function accepts 2 arrays. What do the 2 arrays mean? Is the first one required while the second one optional?

Relevant documentation: https://libvirt.org/formatdomain.html#hard-drives-floppy-disks-cdroms

**Comment by AshleyYakeley** [comment]
OK, this should work. Reopen if it doesn't, or you can make a PR.

For `subelem`, first array is XML attributes, second is XML elements.
