### ISSUE TITLE
Feature Request: qemu override support

### ISSUE THREAD

**Issue by pharra** [AshleyYakeley/NixVirt#36]
QEMU command line: libvirt `qemu-system-x86_64: -set device.hostdev0.x-vga=on: there is no device "hostdev0" defined` qemu-6.2 can use this method [text](https://gitlab.com/qemu-project/qemu/-/issues/787 "6.2.0 Regression with Intel GVT-g"),but 7.0 it does't work

https://gitlab.com/qemu-project/qemu/-/issues/1015

**Comment by pharra** [comment]
#37

**Comment by AshleyYakeley** [comment]
Merged #37.
