### ISSUE TITLE
VM reboots with each rebuild

### ISSUE THREAD

**Issue by afilini** [AshleyYakeley/NixVirt#57]
Looks similar to #9 but I verified the mac address is not changing. Not sure why this is happening, but at every rebuild (even if the domains config is untouched) all my vms are restarted.

Is that supposed to happen or is it some kind of bug or issue related to my configuration?

**Comment by AshleyYakeley** [comment]
Could you try with `virtualisation.libvirt.verbose = true`? It should show the XML diff that makes it think the XML has changed.

**Comment by afilini** [comment]
Thanks for the quick reply! This is the only difference I see in all my domains (they all use the same configuration):

domain e2c678ac-5ac6-424a-a9a2-b64fd6597264: redefine
domain e2c678ac-5ac6-424a-a9a2-b64fd6597264: changed:
[move, /domain/devices/controller[11], /domain/devices[1], 6]
domain e2c678ac-5ac6-424a-a9a2-b64fd6597264: deactivate

**Comment by AshleyYakeley** [comment]
OK, this should be fixed now.
