### ISSUE TITLE
Cloud Hypervisor support?

### ISSUE THREAD

**Issue by matdibu** [AshleyYakeley/NixVirt#74]
Cloud Hypervisor seems to be supported by libvirt https://libvirt.org/drvch.html

It's not supported by NixVirt, right? I can work on that if you want

**Comment by AshleyYakeley** [comment]
What needs to be done?

**Comment by matdibu** [comment]
just a new domain schema in generate-xml, right?

**Comment by AshleyYakeley** [comment]
It shouldn't even need that. You just pass in a different connection URI.

If you're using CH, I recommend you just try it out and create a PR for anything NixVirt is missing.

**Comment by matdibu** [comment]
but then there would be a lot of options that don't do anything or just don't work on a CH vm

although it could be argued that it's user error to pass bad configs to NixVirt

btw, what do you think of #65 ?

**Comment by matdibu** [comment]
I'll drop it for now, it's too early to use CH in libvirt

> The Cloud Hypervisor driver in libvirt is in its early stage under active development only supporting a limited number of Cloud Hypervisor features.

https://libvirt.org/drvch.html
